### PR TITLE
Use circle for deploys

### PR DESCRIPTION
**Pull request by ccnixon**

### CODE REVIEW

**Comment by ccnixon** [comment]
Hey @f2prateek - let me know what you think of this so far. I'm having trouble getting the caching to work. Also having sporatic issues with this error:

image

**Comment by f2prateek** [comment]
cc @fathyb for the simulator error - he mentioned running into something similar for analytics-ios.

**Comment by fathyb** [comment]
Yes we also had this when migrating to Circle 2. Seems like running `xcrun simctl list` just after the `checkout` step fixes it.

**Comment by ccnixon** [comment]
Thanks @fathyb. Were you able to figure out how to cache dependencies?

**Pull request merged**
