### PR TITLE
Dynamic imports in order to ship dependency into Swift private / public podspec.

### PR DESCRIPTION
**Pull request by ldi13**
Hello Segment team,

Here is a pull request in order to ship the Segment_Amplitude dependency into my Swift private podspec.

Thanks by advance for your return,

Best regards,

Lorenzo.

### CODE REVIEW

**Comment by ldi13** [comment]
Hello Segment team,

Could you tell me if this pull request is OK with you, and could be packaged in a new version of Segment_Amplitude pod (1.1.2 for example) ?

Thank you very much for your feedback,

Best regards,

Lorenzo.

**Comment by f2prateek** [comment]
@ldi13 Thanks for the PR, I need to do some additional testing to ensure it doesn't break compatibility. Is there any documentation on this feature that explains why we need this change for the purpose you've mentioned?

**Comment by ldi13** [comment]
Hello @f2prateek,

Thanks for your answer.
Here is an interesting thread detailing the usefulness of @import vs. #import : 

http://stackoverflow.com/questions/18947516/import-vs-import-ios-7

Basically, If you want to create a pod including your cocoapods dependencies (Amplitude-iOS, Segment_Amplitude, Analytics, etc...) into a private / public podspec that uses Swift, you have to declare public headers if you want #import <Analytics/*.h>, or #import <Amplitude-iOS/*.h> to be recognized during compiling phase. Generally, it means that you have to make static imports inside your pod.

Because I want Amplitude-iOS, Segment_Amplitude, Analytics, to be modules in my Swift podspec, and not static imports, I have to declare them inside the headers with @import in order to not have compiling errors.

Hope it will convince you :)

Don't hesitate if you need more explanations, or if you need me to clarify some points.

Once again, thank you very much for you support,

Best regards,

Lorenzo.

**Comment by f2prateek** [comment]
Sorry for the delay - do we need to create a module map for us (and even Amplitude since I didn't find on in their repo)?

**Comment by ldi13** [comment]
Hello @f2prateek,

I'm not familiar with the concept of module map.
I'm not sure you have to, but it's purely hypothetical.

Here is what I found regarding module map on cocoa pods website specification:
https://guides.cocoapods.org/syntax/podspec.html#module_map

Hope it helps.

Thanks,

Lorenzo.

**Comment by hankim813** [comment]
@f2prateek ping!

**Comment by ladanazita** [comment]
Closing due to inactivity.

**Pull request closed without merging**
