### PR TITLE
Specify the version Amplitude to depend on

### PR DESCRIPTION
**Pull request by christianYoopies**
Current merge is supposed to resolve the problem of non-building the project after making 

`pod update/carthage update`

due to major update of 'Amplitude'. 

Thank you in advance for reviewing,

Regards

### CODE REVIEW

**Comment by christianYoopies** [comment]
Merging to master and further creating of a tag would highly appreciated

**Comment by christianYoopies** [comment]
@migs647 @bsneed @briemcnally

**Comment by bsneed** [comment]
@christianYoopies thanks!  We don't want to pin analytics-ios versions, but if you can pull that bit out, I can merge this and put an update out.  Thanks so much for the fix!

**Comment by christianYoopies** [comment]
@bsneed No problem, I cleaned up the Pull Request so it now only deals with Amplitude. Thank you:) I will be notified when you will merge and tag;)

**Review by bsneed — APPROVED** [review]

**Comment by bsneed** [comment]
Thanks @christianYoopies !  Release getting pushed out shortly.

**Comment by christianYoopies** [comment]
Great, thank you for this @bsneed

**Comment by bsneed** [comment]
Hi @christianYoopies, we ended up putting a hold on this internally.  For the meantime, you can point your pod for this to the master branch here.  We need to do the updates to bring it to Amplitude 6.0 for iOS 14 / IDFA changes.

**Comment by christianYoopies** [comment]
@bsneed Thank your for your answer. 
The thing is that we are referencing to Amplitude in the .podspec file for now and unfortunately there is now other way but to link to a version in it because of cocoa pods restriction(you cannot to specify a concrete branch in .podspec file syntax). 
We are not in a big hurry but having some tag(even a patch tag) in couple of weeks would be very nice for us so the team would have been able to do 'pod update':) 

Thank you again, 
Regards

**Comment by bsneed** [comment]
@christianYoopies What we're going to do is issue a 3.2.1 update with your changes, and roll the amplitude-ios 6.0 support into a 4.0.0 release.  Thanks for your patience on the back and forth with this.  I'll issue a release in just a few minutes.  Quick question though, is there any reason to use 5.2.1 over 5.3.0?

**Comment by christianYoopies** [comment]
@bsneed Well I believe there is no vicious reason to say 5.2.1 over 5.3.0 from what I see in the changelog of version 5.3.0.
~> 5.2.1 will get 5.3.0 for all the users finally. I did put 5.2.1 because 5.2.1 was in our Podfile.lock here locally:)
I can do another PR with ~> 5.3.0 if you wish, or you can do the update directly to master for the things to go faster as it is a tiny change ;)

**Comment by bsneed** [comment]
@christianYoopies ok, gotcha.  One additional question.  We pulled amplitude-ios 6.0 and didn't see any incompatibilities there, just that they stopped collecting IDFA being the only change.  Can you elaborate on what you're seeing re Carthage there?

**Comment by christianYoopies** [comment]
@bsneed Let me check

**Comment by christianYoopies** [comment]
@bsneed I will check carefully and let you know asap

**Comment by christianYoopies** [comment]
@bsneed
Segment_build_error

 This is an error we have, sorry for late response

**Pull request merged**
