### PR TITLE
Add SPM Support

### PR DESCRIPTION
**Pull request by mcostasilva**

### CODE REVIEW

**Comment by rwgrier** [comment]
Any word on either getting this PR looked at or adding SPM support to this library? 

Maybe @bsneed?

**Comment by bsneed** [comment]
Thanks for the PR @mcostasilva, and thanks for the ping @rwgrier!  I didn't see this come in.  I can probably get this in next week.  However, just a heads up, when analytics-swift moves out of beta (very soon), we'll be deprecating analytics-ios and many of these destinations.  Analytics-Swift is SPM only and does include an Amplitude plugin, which lets it work via cloud mode and doesn't need the Amplitude SDK in any way.

**Review by bsneed — APPROVED** [review]

**Comment by bsneed** [comment]
Release coming shortly ...

**Comment by bsneed** [comment]
Done!

**Pull request merged**
