### PR TITLE
Update Amplitude to Support iOS 14 

### PR DESCRIPTION
**Pull request by briemcnally**
Update Amplitude SDK to 6.0.0 
Update Analytics SDK  to 4.x 

More details here: https://paper.dropbox.com/doc/iOS14-Updates-X-Pillar-Async-Sync--A6ZjsHgr4B~XNyEhAKAIm7v6Ag-U7d4UKyHjltcy33hChUtd

### CODE REVIEW

**Comment by cerupcat** [comment]
What's the status of getting this merged?

**Comment by bsneed** [comment]
@cerupcat more changes are forthcoming.  looking at EOW.

**Comment by cerupcat** [comment]
Great! Thanks for the update. :D

**Comment by bsneed** [comment]
This PR is no longer necessary.  See `master`.

Version 3.2.1 is out on Cocoapods now.

**Pull request closed without merging**
