### PR TITLE
relaxes Analytics dependency

### PR DESCRIPTION
**Pull request by ladanazita**
Resolves conflict:

### CODE REVIEW

**Review by tonyxiao — APPROVED** [review]
LGTM

**Comment by f2prateek** [comment]
Hmmm, I don't think this is quite right. Something else is going on in your sample (can you share the profile and podfile.lock)?

This pod should use anything over 3.2, so it's weird that it's forcing 3.2.0

**Comment by tonyxiao** [comment]
Ooops, thanks for pointing that out. @ladanazita can you add a bit more info?

**Comment by f2prateek** [comment]
Ah the issue is in the error message.

The user is using 1.3.0 of this integration. The requirement was relaxed in 1.4.0 https://github.com/segment-integrations/analytics-ios-integration-amplitude/commit/a3299acf152bf68ed1e7c426359414f881f289be

**Pull request closed without merging**
